# == Schema Information
#
# Table name: roles
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  resource_id   :integer
#  resource_type :string(255)
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

class Role < ActiveRecord::Base
    
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
   
  
end


#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: roles
#
# * id            :integer         not null
#   name          :string(255)
#   resource_id   :integer
#   resource_type :string(255)
#   created_at    :datetime        not null
#   updated_at    :datetime        not null
#
#  Indexes:
#   index_roles_on_name                                    name
#   index_roles_on_name_and_resource_type_and_resource_id  name,resource_type,resource_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
